//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTDonHangXuat
    {
        public string ID_CTDH { get; set; }
        public string ID_SP { get; set; }
        public string ID_DHX { get; set; }
        public Nullable<int> CT_SoLuong { get; set; }
        public Nullable<decimal> CT_ThanhTien { get; set; }
    
        public virtual DonHangNhap DonHangNhap { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
