//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangNhap()
        {
            this.CTDonHangXuats = new HashSet<CTDonHangXuat>();
        }
    
        public string ID_DHN { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string ID_NV { get; set; }
        public string Ten_NV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHangXuat> CTDonHangXuats { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
