//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPhamKho
    {
        public string ID_SPK { get; set; }
        public string ID_SP { get; set; }
        public string ID_K { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual Kho Kho { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
